version: 0.2

run-as: root
env:
  variables:
    foo: "bar"
  git-credential-helper: yes

phases:
  install:
    commands:
      - TOKEN=`curl "http://127.0.0.1:7831/api/v1/git/creds?auth_token=$CODEBUILD_AUTH_TOKEN&repo=https://github.com/aws/somerepothatdoesnotexist"`
      - echo "Token result: $TOKEN"
